# Theme sourced from https://github.com/pages-themes/hacker

remote_theme: pages-themes/hacker
#remote_theme: pages-themes/hacker@v0.2.0
#theme: jekyll-theme-hacker

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: Cyber Antonio

description: Page to find out what I am going to do with it.

show_downloads: false

#google_analytics: [Your Google Analytics tracking ID]

autor: Antonio Feijao UK
